### ISSUE TITLE
You've been tunced

### ISSUE THREAD

**Issue by lukebakken** [macintux/jam#6]
https://github.com/macintux/jam/blob/master/src/jam.erl#L661-L663

I am still mystified by what is considered to be good code formatting in Erlang, because it doesn't seem to line up with my expectations from other languages.

That being said, `?GREGORIAN_MAGIC).` dangles in the wind.

**Comment by macintux** [comment]
Believe it or not, that's Emacs' standard indentation choice in that circumstance. Fixed.
